# =============================================
# App
# =============================================
spring.application.name=Inventario
server.port=8080

# =============================================
# Conexión a PostgreSQL
# =============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/db_inventario
spring.datasource.username=postgres
spring.datasource.password=122511

# =============================================
# Configuración de Swagger UI
# =============================================

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true


## 3. Levanta el proyecto y abre en tu navegador

http://localhost:8080/swagger-ui.html